### ISSUE TITLE
顯示的數值如果過期一定的時間，其數值顯示會加上刪除號

### ISSUE THREAD

**Issue by Jyneda** [IoTtalk/FarmDashboard#10]
顯示的數值如果過期一定的時間，其數值顯示會加上刪除號

admin可以設定該過期時間(預設為1hr)，設定方式放在網頁(較優)，或是config file皆可。

**Comment by Ksoy** [comment]
@Jyneda 有哪一個sensor是已經過期的嗎？

**Comment by Jyneda** [comment]
只要點下more information一片空白的就是，寶山3場的最後一個薑黃產量，就是過期的

**Comment by Ksoy** [comment]
5cdc749
目前為一小時不能修改
