### ISSUE TITLE
在Dashboard上加入Sensor，會自動在models.py內自動新增對應的DB結構

### ISSUE THREAD

**Issue by Jyneda** [IoTtalk/FarmDashboard#14]

**Comment by Ksoy** [comment]
我想了一天，怎麼想都不覺得這個功能應該做誒，
資料庫可以被隨意新增表這件事太可怕了，
而且在models的版本控制上也一定會發生衝突。

感覺正確的做法應該是

1.  df的表要先規定好，前端管理員想要加不存在的就要通知後端管理員去做，就是原本的做法，不過好像都是同一個人？這麼看來sensor好像不能讓人隨意新增

2. 用mysql的partition功能，將所有df的表融合成一張表，不過我沒測過效能，sqlalchemy也不支援partition

**Comment by Jyneda** [comment]
我的想法很單純，就是盡量都是在GUI上實現，而不需要把後台server登入帳密隨意給人。   只要符合這方向，其他部分我都覺得還好。  然後如果有  "管理者" 在GUI上就會把DB弄炸，那讓他去碰models.py，就更肯定會炸掉。

連我去改models.py都會發生很高的機會改完，dashboard 都常開不起來了，然後要仔細看我做錯啥事。  如果交給路人甲管理員去處理，那不就更慘?

然後版本控制，其實models.py只需要放入基本的examples，之後就不用再上傳了。  因為現在github上面的dashboard已經越來越多人用了，不是只有我們使用，所以已經不可將github視為備份用，而是真的用來散布的。
