### ISSUE TITLE
分頁列表提供輸入url(舉例)，以嵌入網頁的功能，並可讓該網頁拿到userId

### ISSUE THREAD

**Issue by Jyneda** [IoTtalk/FarmDashboard#6]
*** 分頁列表提供輸入url(舉例)，以嵌入網頁的功能，並可讓該網頁拿到userId

例如：嵌入RemoteControl網頁，並且在輸入url的欄位中，可填入變數 <userId>，將userId在url內帶入RemoteControl網頁。

PS. 上述分頁列表提供輸入url，這方式只是舉例。  主要能夠實現分頁中可以放入user自己的網頁(例如RemoteControl網頁)，並帶入userId即可

**Comment by Ksoy** [comment]
#7
