### ISSUE TITLE
Dashboard數值警示功能

### ISSUE THREAD

**Issue by Jyneda** [IoTtalk/FarmDashboard#8]
在Dashboard中，再把sensor拉入Field時，多一個range的欄位可以輸入。 之後如果發生數值摔出range的話，就會送訊息到  Alert-I 這個idf，內容是     Sensor name, value

每個DA在註冊時，也要註冊一個Alert-I的IDF。

**Comment by Ksoy** [comment]
a27a663276c3dbdd95907e4b96dbd5d85ba572c3
